### ISSUE TITLE
Einige Rezepte werfen 500 internal server error

### ISSUE THREAD

**Issue by Foaly** [ooovi/fettnapf3000#1]
Wenn man sich auf der Seite https://teamgeil.uber.space/menu/ unten durch die Rezepte klickt werfen die Rezepte [Linsensuppe+brot](https://teamgeil.uber.space/calculate?linsensuppe+brot.txt=10), [Mercimek+brot](https://teamgeil.uber.space/calculate?mercimek+brot.txt=10) und [Wirsing+cheesymash](https://teamgeil.uber.space/calculate?wirsing+cheesymash.txt=10) den Fehler `500 Internal Server Error`.

Wenn ich raten müsste würde ich sagen es liegt am + im Namen.

Bitte schnell fixen! Tool ist 5/5 ⭐, aber dadurch leider nur 1/5 ⭐. War schon mitten am Kochen und jetzt ist alles in die Hose gegangen. Konnte Rezept nicht öffnen. Workshop musste abgesagt werden. Wir haben jetzt Döner bestellt. Grüße aus Hamburg

**Comment by ooovi** [comment]
oh lecker döner

**Comment by Foaly** [comment]
🧆
